easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation

mov_meta_edit:
    resource: "@MOVMetaEditBundle/Controller/"
    type:     annotation

avi_meta_edit:
    resource: "@AVIMetaEditBundle/Controller/"
    type:     annotation

no_time_to_wait:
    resource: "@NoTimeToWaitBundle/Controller/"
    type:     annotation

ollistd:
    resource: "@OllistdBundle/Controller/"
    type:     annotation

media_bin:
    resource: "@MediaBinBundle/Controller/"
    type:     annotation

dv_analyzer:
    resource: "@DVAnalyzerBundle/Controller/"
    type:     annotation

qc_tools:
    resource: "@QCToolsBundle/Controller/"
    type:     annotation

bwf_meta_edit:
    resource: "@BWFMetaEditBundle/Controller/"
    type:     annotation

media_conch:
    resource: "@MediaConchBundle/Controller/"
    type:     annotation

media_conch_online:
    resource: "@MediaConchOnlineBundle/Controller/"
    type:     annotation

media_trace:
    resource: "@MediaTraceBundle/Controller/"
    type:     annotation

raw_cooked:
    resource: "@RAWcookedBundle/Controller/"
    type:     annotation

dvrescue:
    resource: "@DVRescueBundle/Controller/"
    type:     annotation

leavesd:
    resource: "@LeaveSDBundle/Controller/"
    type:     annotation

embarc:
    resource: "@EmbARCBundle/Controller/"
    type:     annotation

support_us:
    resource: "@SupportUsBundle/Controller/"
    type:     annotation

payment:
    resource: "@PaymentBundle/Controller/"
    type:     annotation

vote:
    resource: "@VoteBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

media_info:
    resource: "@MediaInfoBundle/Controller/"
    type:     annotation
